
services:
  db:
    image: mysql:8.0
    container_name: apipapas_mysql
    restart: always
    command: --local-infile=1
    environment:
      MYSQL_ROOT_PASSWORD: MyRootPassword!
      MYSQL_DATABASE: apidepapas
      MYSQL_USER: ApiUser
      MYSQL_PASSWORD: ApiDePapas_G6_Logistica
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apipapas_api
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "server=db;port=3306;database=apidepapas;user=ApiUser;password=ApiDePapas_G6_Logistica;ConvertZeroDateTime=True;AllowLoadLocalInfile=true"
      MYSQL_PASSWORD: ApiDePapas_G6_Logistica
      Authentication__Keycloak__Authority: "http://host.docker.internal:8080/realms/ds-2025-realm"
      Keycloak__TokenEndpoint: "http://host.docker.internal:8080/realms/ds-2025-realm/protocol/openid-connect/token"
      Keycloak__ClientId: "grupo-06"
      Keycloak__ClientSecret: "8dc00e75-ccea-4d1a-be3d-b586733e256c"
    ports:
      - "5002:8080"
    volumes:
      - ./db-init:/app/db-init
      - ./docs/csvs:/app/csvs
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: ./frontend-dashboard
      dockerfile: Dockerfile
    container_name: apipapas_frontend
    depends_on:
      api:
        condition: service_started
    ports:
      - "3000:5173"
    environment:
      VITE_PUBLIC_API_URL: http://localhost:5002/api
      VITE_PRIVATE_API_URL: http://api:8080/api
      PUBLIC_BACKEND_API_KEY: "your-super-secret-dashboard-api-key"
    volumes:
      - ./frontend-dashboard:/app
      - /app/node_modules
    command: npm run dev

volumes:
  db_data: